name: flutter_avatars_bottts
description: Flutter Avatar - Bottts (render svg on the fly at high speed)
version: 1.0.0
author: Abhijat Saxena
homepage: https://github.com/AbhijatSaxena/flutter_avatars_bottts/blob/master/README.md

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.1
  random_color: ^1.0.5  

dev_dependencies:
  flutter_test:
    sdk: flutter